ci:
  skip: [pyright]
  autoupdate_schedule: quarterly
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # File names
      - id: check-case-conflict
      # File formats
      - id: pretty-format-json
      - id: check-json
      - id: check-toml
      - id: check-yaml
      # Executables
      - id: check-executables-have-shebangs
        exclude: dev-env
      - id: check-shebang-scripts-are-executable
      # Git shenanigans
      - id: check-merge-conflict
      - id: check-added-large-files
      # Python issues
      - id: check-ast
      - id: debug-statements
      # Whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: "3.2.0"
    hooks:
      - id: sqlfluff-fix
        args: ["--dialect=postgres"]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.381
    hooks:
      - id: pyright
        additional_dependencies:
          - aiopg==1.4.0
          - anyio==4.5.0
          - asgiref==3.8.1
          - attrs==24.2.0
          - contextlib2==21.6.0
          - croniter==3.0.3
          - django-stubs==5.1.0
          - django==5.1.1
          - importlib-resources==6.4.5
          - psycopg2-binary==2.9.9
          - psycopg[pool]==3.2.2
          - python-dateutil==2.9.0.post0
          - sphinx==7.1.2
          - sqlalchemy==2.0.35
          - typing-extensions==4.12.2
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
      - id: ruff-format
  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.2
    hooks:
      - id: doc8
  - repo: https://github.com/ewjoachim/poetry-to-pre-commit
    rev: 2.2.0
    hooks:
      - id: sync-repos
        args: [--map=pyright-python=pyright, --map=ruff-pre-commit=ruff]

      - id: sync-hooks-additional-dependencies
        args: ['--bind=pyright=main,types']
